# Generated by Django 2.0.2 on 2018-02-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='download_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(default=0, verbose_name='year published'),
        ),
    ]
