# Generated by Django 2.0.2 on 2018-02-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20180213_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, to='books.Category'),
        ),
    ]
